@startuml

left to right direction

actor "Пользователь" as User

rectangle "MDI Paint" {
    package "Управление файлами" {
        User -- (Создать новый холст)
        User -- (Открыть изображение)
        User -- (Сохранить изображение)
        User -- (Закрыть вкладку)
        (Закрыть вкладку) ..> (Получить уведомление о несохраненных изменениях) : <<Включает>>
    }

    package "Инструменты рисования" {
        User -- (Выбрать инструмент)
        (Выбрать инструмент) --|> (Использовать Перо)
        (Выбрать инструмент) --|> (Использовать Ластик)
        (Выбрать инструмент) --|> (Нарисовать Линию)
        (Выбрать инструмент) --|> (Нарисовать Эллипс)
        (Выбрать инструмент) --|> (Использовать Заливку)
        (Выбрать инструмент) --|> (Добавить Текст)
        (Выбрать инструмент) --|> (Нарисовать Смайлик)
    }

    package "Редактирование и просмотр" {
        User -- (Изменить цвет кисти)
        User -- (Изменить размер кисти)
        User -- (Увеличить масштаб)
        User -- (Уменьшить масштаб)
    }
    
    package "Интерфейс" {
        User -- (Открыть окно 'О программе')
        User -- (Использовать горячие клавиши)
    }
}

@enduml

